version: "3.8"
services:
  # Conteneur de la base de données mysql
  db:
    image: mysql
    container_name: mysql_Don_Echange
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    networks:
      - tutorial

  # Conteneur Phpmyadmin
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin_Don_Echange
    restart: always
    depends_on:
      - db
    ports:
      - 8010:80
    environment:
      PMA_HOST: db
    networks:
      - tutorial

  # Conteneur de l'application laravel
  www:
    build: docker/php
    container_name: Don_Echange
    ports:
      - "8002:80"
    volumes:
      - ./docker/php/vhosts:/etc/apache2/sites-enabled
      - ./:/var/www/html
    restart: always
    networks:
      - tutorial

networks:
  tutorial:

volumes:
  db-data:
